project:
  type: website
  output-dir: docs

website:
  title: "Kate OBrien's ePortfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: portfolio_project/OBrienK_dev_and_planning.qmd
        text: "Portfolio Project"
format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

